nginx:
  build: ./nginx
  ports:
    - "80:80"
  links:
    - "phpfpm"
  volumes:
    - ./htdocs/:/var/www/html/
    - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
phpfpm:
  build: ./phpfpm
  ports:
    - "9000:9000"
  volumes:
    - ./htdocs/:/var/www/html/
  links:
    - "mysql"
phpmyadmin:
  image: phpmyadmin/phpmyadmin
  container_name: phpmyadmin
  environment:
    PMA_HOST: "mysql"
    PMA_USER: "root"
    PMA_PASSWORD: "123456"
  restart: always
  ports:
    - 8081:80
  volumes:
    - /sessions
  links:
      - "mysql"
mysql:
  build: ./mysql
  ports:
    - "3306:3306"
  volumes:
    - ./mysql/data/:/var/lib/mysql/
  environment:
    MYSQL_ROOT_PASSWORD: 123456
